(() => {const E=window.EV;E.ready(async()=>{
 const root=document.querySelector('[data-ev-ids]');if(!root)return;
 try{const[all,map,dates]=await Promise.all([E.data(),E.routes(),import('/trial-data.js')]);const ids=new Set(root.dataset.evIds.split(',')),rows=all.filter(r=>ids.has(String(r.id))),nodes=new Map([...document.querySelectorAll('#ev-list>.ev-card')].map(n=>[n.dataset.id,n])),list=document.getElementById('ev-list'),count=document.getElementById('ev-count'),q=document.getElementById('ev-q'),more=document.getElementById('ev-more'),sort=document.getElementById('ev-sort'),view=document.getElementById('ev-view'),chips=document.getElementById('ev-chips'),empty=document.getElementById('ev-empty'),filters=[...document.querySelectorAll('[data-ev-filter]')];let limit=24,timer;const keys={area:'esp',topic:'tema',year:'anio',journal:'revista',type:'tipo'},values={area:r=>E.areas(r),topic:r=>r.temas||[],year:r=>[String(r.anio)],journal:r=>[r.revista],type:r=>[r.tipo_estudio]};
 for(const r of rows){const inferred=E.inferSubspecialty(r),node=nodes.get(String(r.id));if(inferred&&node&&!node.querySelector('[data-ev-subspecialty]')){const badge=document.createElement('span');badge.className='ev-tag';badge.dataset.evSubspecialty='true';badge.textContent=inferred;node.querySelector('.ev-meta').prepend(badge,document.createElement('br'))}}
 for(const f of filters){const unique=[...new Set(rows.flatMap(values[f.dataset.evFilter]).filter(Boolean))].sort((a,b)=>f.dataset.evFilter==='year'?Number(b)-Number(a):a.localeCompare(b,'es'));f.innerHTML='<option value="">Todos</option>'+unique.map(v=>'<option value="'+E.esc(v)+'">'+E.esc(v)+' ('+rows.filter(r=>values[f.dataset.evFilter](r).includes(v)).length+')</option>').join('')}
 function fromURL(){const p=new URLSearchParams(location.search);q.value=p.get('q')||'';for(const f of filters)f.value=p.get(keys[f.dataset.evFilter])||'';sort.value=p.get('orden')||'date';const dense=p.get('vista')==='lista';root.classList.toggle('ev-dense',dense);view.setAttribute('aria-pressed',String(dense));view.textContent=dense?'Tarjetas':'Lista densa';limit=Math.max(24,Number(p.get('n'))||24)}
 function url(){const u=new URL(location.href);for(const k of ['q',...Object.values(keys),'orden','vista','n'])u.searchParams.delete(k);if(q.value.trim())u.searchParams.set('q',q.value.trim());for(const f of filters)if(f.value)u.searchParams.set(keys[f.dataset.evFilter],f.value);if(sort.value!=='date')u.searchParams.set('orden',sort.value);if(root.classList.contains('ev-dense'))u.searchParams.set('vista','lista');if(limit>24)u.searchParams.set('n',String(limit));return u}
 function render(push=false){let chosen=rows.filter(r=>(!q.value.trim()||E.searchable(r).includes(E.norm(q.value.trim())))&&filters.every(f=>!f.value||values[f.dataset.evFilter](r).includes(f.value)));chosen=chosen.slice().sort(sort.value==='title'?(a,b)=>a.titulo.localeCompare(b.titulo,'es'):sort.value==='journal'?(a,b)=>a.revista.localeCompare(b.revista,'es')||a.titulo.localeCompare(b.titulo,'es'):dates.compareTrialDates);const selected=new Set(chosen.slice(0,limit).map(r=>String(r.id)));for(const r of chosen){const n=nodes.get(String(r.id));if(n)list.append(n)}for(const[id,n]of nodes)n.hidden=!selected.has(id);count.textContent=chosen.length+' de '+rows.length+' resúmenes';more.hidden=chosen.length<=limit;empty.hidden=chosen.length!==0;chips.innerHTML=filters.filter(f=>f.value).map(f=>'<button class="ev-chip" type="button" data-ev-clear="'+f.id+'" aria-label="Quitar filtro '+E.esc(f.value)+'">'+E.esc(f.value)+' ×</button>').join('')+(q.value?'<button class="ev-chip" type="button" data-ev-clear="ev-q">Quitar búsqueda ×</button>':'');if(push&&url().href!==location.href)history.pushState(null,'',url())}
 function update(){limit=24;render(true)}
 q.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(update,120)});for(const f of filters)f.onchange=update;sort.onchange=()=>render(true);view.onclick=()=>{const on=root.classList.toggle('ev-dense');view.textContent=on?'Tarjetas':'Lista densa';view.setAttribute('aria-pressed',String(on));render(true)};more.onclick=()=>{limit+=24;render(true)};chips.onclick=e=>{const b=e.target.closest('[data-ev-clear]');if(b){document.getElementById(b.dataset.evClear).value='';update()}};
 root.querySelector('[data-ev-preset]')?.addEventListener('click',e=>{q.value='';for(const f of filters)f.value=f.dataset.evFilter==='area'?'Medicina Crítica':f.dataset.evFilter==='year'?e.currentTarget.dataset.evPreset:'';update()});
 window.addEventListener('popstate',()=>{fromURL();render()});fromURL();render();

 }catch(error){E.archiveError=error;document.getElementById('ev-count').textContent='Archivo disponible · filtros no disponibles. Recarga para reintentar.'}
})})();

