(() => {const E=window.EV;
const humanDate=value=>{const m=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})$/),months=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];return m&&months[Number(m[2])-1]?Number(m[3])+' de '+months[Number(m[2])-1]+' de '+m[1]:String(value||'')};
const editorialDates=r=>{const parts=[];for(const [key,label]of [['fecha_publicacion_resumen','Publicado en Resúmenes Trials'],['fecha_revision','Última revisión']]){const value=r[key]||(key==='fecha_revision'?r.actualizado:'');if(value)parts.push('<span>'+label+': <time datetime="'+E.esc(value)+'">'+E.esc(humanDate(value))+'</time></span>')}return parts.length?'<div class="ev-editorial-dates">'+parts.join(' · ')+'</div>':''};
const cutDescription=text=>{if(text.length<=158)return text;const cut=text.slice(0,159),space=cut.lastIndexOf(' ');return (space>100?cut.slice(0,space):text.slice(0,158)).trim()+'…'};
function updateMetadata(r,path,brief){
 const base='https://resumenestrials.com',url=base+path,title=E.plain(r.titulo)+(brief?' · resumen breve':'')+' · Resumenes Trials',description=E.plain(r.objetivo||r.hallazgo||'Resumen crítico en español de un ensayo clínico aleatorizado.').replace(/\s+/g,' ').trim();
 document.title=title;let canonical=document.querySelector('link[rel=canonical]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical)}canonical.href=url;
 for(const [selector,value]of [['meta[name=description]',cutDescription(description)],['meta[name=robots]','noindex,follow,max-image-preview:large'],['meta[property="og:title"]',title],['meta[property="og:description"]',cutDescription(description)],['meta[property="og:url"]',url],['meta[name="twitter:title"]',title],['meta[name="twitter:description"]',cutDescription(description)]])document.querySelector(selector)?.setAttribute('content',value);
 const topics=r.temas||[],about=[r.especialidad_principal,r.especialidad_secundaria,E.inferSubspecialty(r),...topics].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).map(name=>({'@type':'MedicalEntity',name}));
 const article={'@type':'MedicalScholarlyArticle',headline:E.plain(r.titulo),description:cutDescription(description),inLanguage:'es',mainEntityOfPage:url,url,publisher:{'@type':'Organization',name:'Resumenes Trials',url:base+'/',logo:{'@type':'ImageObject',url:base+'/logo.png'}}};
 if(r.fecha)article.datePublished=r.fecha;if(r.autor)article.author={'@type':'Person',name:E.plain(r.autor)};if(r.revista)article.isPartOf={'@type':'Periodical',name:E.plain(r.revista)};if(r.original)article.isBasedOn=r.original;if(r.doi)article.identifier=article.sameAs='https://doi.org/'+E.plain(r.doi);if(about.length)article.about=about;if(topics.length)article.keywords=topics.join(', ');
 const crumbs={'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Índice',item:base+'/'},{'@type':'ListItem',position:2,name:r.especialidad_principal||'Resúmenes',item:base+'/'}]},ld=document.getElementById('structured-data');if(ld)ld.textContent=JSON.stringify({'@context':'https://schema.org','@graph':[article,crumbs]});
}
const facts=r=>E.facts(r);
function markup(r,path,brief){return '<section data-ev-reader="'+r.id+'" data-ev-brief="'+brief+'"><nav class="ev-breadcrumb" aria-label="Ruta"><a href="/" data-ev-return>← Volver a la lista</a><a href="/metodologia/">Metodología</a></nav><header class="ev-reading-head"><span class="ev-eyebrow">'+E.esc(r.tipo_estudio)+' / '+E.esc(r.anio)+'</span><h1 data-ev-field="titulo">'+E.esc(r.titulo)+'</h1><p class="ev-meta"><span data-ev-field="autor">'+E.esc(r.autor)+'</span> · <span data-ev-field="revista">'+E.esc(r.revista)+'</span> · <span data-ev-field="fecha">'+E.esc(humanDate(r.fecha))+'</span></p><p data-ev-field="hallazgo" class="ev-lead">'+E.safe(r.hallazgo)+'</p>'+editorialDates(r)+'</header>'+facts(r)+'<div class="ev-toolbar" role="region" aria-label="Controles de lectura"><div class="ev-version"><a href="'+E.esc(path)+'"'+(!brief?' aria-current="page"':'')+'>Completo</a><a href="/resumen.html?id='+r.id+'&amp;v=corto"'+(brief?' aria-current="page"':'')+'>Breve</a></div><button type="button" data-ev-sections>Secciones</button><button type="button" data-ev-pdf>↓ PDF</button><button type="button" data-ev-format aria-label="Elegir formato de PDF">Formato</button><button type="button" data-ev-save>Guardar</button><button type="button" data-ev-focus aria-pressed="false">Modo lectura</button><button type="button" data-ev-font aria-label="Cambiar tamaño de letra">A+</button></div><progress class="ev-progress" max="100" value="0" aria-label="Progreso de lectura"></progress><div class="ev-reader-grid"><article class="ev-body">'+E.safe(r[brief?'corto':'cuerpo'])+'</article><aside class="ev-rail"><p class="ev-eyebrow">En esta página</p><nav data-ev-toc aria-label="Secciones del artículo"></nav></aside></div><div class="ev-endmatter"><p class="ev-original">Artículo original: '+(String(r.original).startsWith('https://')?'<a href="'+E.esc(r.original)+'" target="_blank" rel="noopener noreferrer">'+E.esc(r.original)+'</a>':E.esc(r.original))+'</p><nav class="ev-neighbors" aria-label="Continuidad de lectura" data-ev-neighbors></nav><section class="ev-related"><h2>Evidencia relacionada</h2><ul class="ev-list" data-ev-related></ul></section><p class="ev-meta" id="ev-reader-status" role="status"></p></div></section>'}
E.ready(async()=>{
 if(!document.body.classList.contains('ev-reader'))return;
 let all,map,r,reader,brief=false;const dynamic=document.getElementById('ev-dynamic-reader');
 try{[all,map]=await Promise.all([E.data(),E.routes()]);if(dynamic){const p=new URLSearchParams(location.search),id=p.get('id');r=all.find(r=>String(r.id)===id);if(!r){document.title='Resumen no encontrado · Resúmenes Trials';dynamic.innerHTML='<section class="ev-notice"><h1>Resumen no encontrado</h1><p>El identificador no corresponde a un ensayo disponible.</p><a class="ev-button" href="/">Volver al archivo</a></section>';return}brief=p.get('v')==='corto'&&!!r.corto;dynamic.innerHTML=markup(r,map[String(r.id)].path,brief);updateMetadata(r,map[String(r.id)].path,brief)}
 reader=document.querySelector('[data-ev-reader]');if(!reader)return;r??=all.find(x=>String(x.id)===reader.dataset.evReader);brief=reader.dataset.evBrief==='true';if(!r)throw Error('Resumen no disponible');
 const article=reader.querySelector('article'),headings=[...article.querySelectorAll('h2')],toc=reader.querySelector('[data-ev-toc]'),progress=reader.querySelector('progress'),status=document.getElementById('ev-reader-status');
 E.prose(reader);
 headings.forEach((h,i)=>h.id='ev-section-'+(i+1));const links=headings.map((h,i)=>'<a href="#'+h.id+'">'+String(i+1).padStart(2,'0')+' · '+E.esc(h.textContent)+'</a>').join('');toc.innerHTML=links;
 const dialog=document.createElement('dialog');dialog.id='ev-sections';dialog.className='ev-dialog';dialog.setAttribute('aria-labelledby','ev-sections-title');dialog.innerHTML='<div class="ev-dialog-head"><h2 id="ev-sections-title">Secciones del ensayo</h2><button type="button" aria-label="Cerrar">×</button></div><div class="ev-dialog-body"><nav class="ev-dialog-list" aria-label="Índice de secciones">'+links+'</nav></div>';document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();reader.querySelector('[data-ev-sections]').onclick=()=>dialog.showModal();dialog.querySelectorAll('a').forEach(a=>a.onclick=()=>{dialog.close();const h=document.getElementById(a.hash.slice(1));h.tabIndex=-1;setTimeout(()=>h.focus({preventScroll:true}),0)});
 const indexLinks=[...toc.querySelectorAll('a'),...dialog.querySelectorAll('nav a')];let activeSection;
 const update=()=>{const rect=article.getBoundingClientRect(),total=Math.max(1,article.offsetHeight-innerHeight*.5);progress.value=Math.max(0,Math.min(100,-rect.top/total*100));const reference=(parseFloat(getComputedStyle(document.documentElement).scrollPaddingTop)||0)+(parseFloat(getComputedStyle(headings[0]).scrollMarginTop)||0)+2;let current=headings[0];for(const heading of headings){if(heading.getBoundingClientRect().top>reference)break;current=heading}if(current.id!==activeSection){activeSection=current.id;for(const a of indexLinks){if(a.hash==='#'+activeSection)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')}}};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update,{passive:true});update();
 const focus=reader.querySelector('[data-ev-focus]');focus.onclick=()=>{const on=document.body.classList.toggle('ev-focus');focus.setAttribute('aria-pressed',String(on));try{localStorage.setItem('ev-focus',String(on))}catch{}update()};
 const font=reader.querySelector('[data-ev-font]');let size=0;try{size=Number(localStorage.getItem('ev-font'))||0;document.body.classList.toggle('ev-focus',localStorage.getItem('ev-focus')==='true');focus.setAttribute('aria-pressed',String(document.body.classList.contains('ev-focus')))}catch{}
 const applyFont=()=>{document.body.classList.toggle('ev-font-small',size===1);document.body.classList.toggle('ev-font-large',size===2);font.setAttribute('aria-label','Cambiar tamaño de letra · '+[20,18,22][size]+' píxeles');update()};applyFont();font.onclick=()=>{size=(size+1)%3;applyFont();try{localStorage.setItem('ev-font',String(size))}catch{}};
 let format=innerWidth<720?'mobile':'a4';const pdf=reader.querySelector('[data-ev-pdf]');pdf.onclick=async()=>{pdf.disabled=true;E.status(status,'Preparando PDF…');try{await E.pdf(r,brief,format);E.status(status,'PDF descargado.')}catch{E.status(status,'No pudimos descargar el PDF. Intenta de nuevo.')}finally{pdf.disabled=false}};
 const fd=document.createElement('dialog');fd.id='ev-pdf-format';fd.className='ev-dialog';fd.setAttribute('aria-labelledby','ev-pdf-title');fd.innerHTML='<div class="ev-dialog-head"><h2 id="ev-pdf-title">Formato del PDF</h2><button type="button" aria-label="Cerrar">×</button></div><div class="ev-dialog-body"><button type="button" data-format="a4">Descargar · Computadora A4</button> <button type="button" data-format="mobile">Descargar · Celular</button><p class="ev-meta">Elige el formato para descargar esta versión.</p></div>';document.body.append(fd);fd.querySelector('button[aria-label]').onclick=()=>fd.close();fd.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{format=b.dataset.format;reader.querySelector('[data-ev-format]').textContent=format==='mobile'?'Celular':'A4';fd.close();pdf.click()});reader.querySelector('[data-ev-format]').onclick=()=>fd.showModal();
 const save=reader.querySelector('[data-ev-save]');let busy=false;save.onclick=async()=>{if(busy)return;busy=true;save.disabled=true;try{const lib=await E.library(),state=await lib.getLibraryState();if(!state.signedIn){location.href='/login.html?next='+encodeURIComponent(location.pathname+location.search);return}const added=await lib.toggleFavorite(r.id);save.textContent=added?'Guardado':'Guardar';save.setAttribute('aria-pressed',String(added));E.status(status,added?'Ensayo guardado en tu biblioteca.':'Ensayo retirado de tu biblioteca.')}catch{E.status(status,'No pudimos actualizar tu biblioteca. Intenta de nuevo.')}finally{busy=false;save.disabled=false}};
 E.library().then(lib=>lib.getLibraryState()).then(state=>{const added=state.signedIn&&state.favorites.includes(String(r.id));save.textContent=added?'Guardado':'Guardar';save.setAttribute('aria-pressed',String(added))}).catch(()=>{});
 const dates=await import('/trial-data.js?v=20261003-laboratorio-v1'),ordered=all.slice().sort(dates.compareTrialDates),index=ordered.findIndex(x=>x.id===r.id);reader.querySelector('[data-ev-neighbors]').innerHTML=(index>0?'<a class="ev-button" href="'+map[String(ordered[index-1].id)].path+'">← Ensayo anterior</a>':'')+'<a class="ev-button" href="/" data-ev-return>Volver a la lista</a>'+(index<ordered.length-1?'<a class="ev-button" href="'+map[String(ordered[index+1].id)].path+'">Ensayo siguiente →</a>':'');
 for(const a of reader.querySelectorAll('[data-ev-return]')){a.href=window.RTReadingContext?.destination()||'/';a.onclick=()=>window.RTReadingContext?.requestReturn()}
 const inferred=E.inferSubspecialty(r);if(inferred){const badge=document.createElement('span');badge.className='ev-tag';badge.dataset.evSubspecialty='true';badge.textContent=inferred;reader.querySelector('.ev-reading-head').append(badge)}
 const pdfLabel=brief?'Descargar resumen breve PDF':'Descargar resumen completo PDF';pdf.setAttribute('aria-label',pdfLabel);pdf.dataset.pdfVersion=brief?'breve':'completo';

 const categories=record=>E.areas(record).filter(s=>['Medicina Crítica','Medicina Interna'].includes(s)),specialty=categories(r),topics=new Set((r.temas||[]).map(E.norm)),clusters=new Set((map[String(r.id)].clusters||[]).map(c=>c.path));
 const rank=all.filter(x=>String(x.id)!==String(r.id)).map(x=>({r:x,s:(map[String(x.id)].clusters||[]).filter(c=>clusters.has(c.path)).length*4+(x.temas||[]).filter(t=>topics.has(E.norm(t))).length*2+categories(x).filter(s=>specialty.includes(s)).length})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s||String(b.r.fecha||'').localeCompare(String(a.r.fecha||''))).slice(0,4);reader.querySelector('[data-ev-related]').innerHTML=rank.map(x=>E.card(x.r,map[String(x.r.id)].path)).join('');
 if(dynamic)import('/reader-advertising.js').then(m=>m.loadReaderAdvertising(r,article)).catch(()=>{});
 }catch(error){E.readerError=error;if(dynamic)dynamic.innerHTML='<section class="ev-notice"><h1>No pudimos cargar el ensayo</h1><a class="ev-button" href="">Reintentar</a> <a class="ev-button" href="/">Volver al archivo</a></section>'}
});
})();

